name: vania
description: Fast, simple, and powerful backend framework for Dart built with
version: 0.6.1
homepage: https://vdart.dev
repository: https://github.com/vania-dart/framework
issue_tracker: https://github.com/vania-dart/framework/issues
documentation: https://vdart.dev/docs/intro
topics: [server, backend, httpserver, framework, web]

screenshots:
  - description: 'Vania web application'
    path: assets/logo.png

environment:
   sdk: '>=3.0.0 <4.0.0'

dependencies:
  crypto: ^3.0.6
  dart_jsonwebtoken: ^2.14.1
  eloquent: ^3.2.1
  mailer: ^6.2.0
  meta: ^1.16.0
  mime: ^1.0.6
  path: ^1.9.1
  sprintf: ^7.0.0
  string_scanner: ^1.4.0
  uuid: ^4.5.1
dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.8
  http: ^1.2.2
  http_parser: ^4.1.1
  build_runner: ^2.4.13
  mockito: ^5.4.4

  